<?php

declare(strict_types=1);

/**
 * Seed CSEC unit-plan drafts into Gibbon Planner units.
 *
 * Dry-run by default:
 *   php scripts/seed-csec-unit-plan-drafts.php
 *
 * Commit writes:
 *   php scripts/seed-csec-unit-plan-drafts.php --commit
 *
 * This script reads docs/unit-plan-drafts/*.json generated by
 * scripts/build-csec-unit-plan-drafts.py. It creates:
 *   - gibbonUnit rows for each detected syllabus unit, duplicated into the
 *     matching Grade 4 and Grade 5 courses.
 *   - gibbonUnitBlock rows for detected specific objectives.
 *   - gibbonOutcome rows for detected general objectives, linked to units via
 *     gibbonUnitOutcome.
 *
 * It does not create gibbonUnitClass or dated gibbonPlannerEntry rows.
 */

require_once __DIR__ . '/../config.php';

$commit = in_array('--commit', $argv, true);
$draftDir = __DIR__ . '/../docs/unit-plan-drafts';
$targetSchoolYearID = '027';
$creatorPersonID = '0000000001';
$yearGroupIDList = '004,005';

$subjectConfigs = [
    'csec-biology' => [
        'category' => 'CSEC Biology',
        'code' => 'BIO',
        'departmentID' => '0003',
        'courseIDs' => ['00000149', '00000184'],
    ],
    'csec-chemistry' => [
        'category' => 'CSEC Chemistry',
        'code' => 'CHEM',
        'departmentID' => '0003',
        'courseIDs' => ['00000152', '00000187'],
    ],
    'csec-english' => [
        'category' => 'CSEC English',
        'code' => 'ENG',
        'departmentID' => '0004',
        'courseIDs' => ['00000159', '00000195'],
    ],
    'csec-geography' => [
        'category' => 'CSEC Geography',
        'code' => 'GEO',
        'departmentID' => '0007',
        'courseIDs' => ['00000164', '00000198'],
    ],
    'csec-integrated-science' => [
        'category' => 'CSEC Integrated Science',
        'code' => 'INTSCI',
        'departmentID' => '0003',
        'courseIDs' => ['00000171', '00000205'],
    ],
    'csec-mathematics' => [
        'category' => 'CSEC Mathematics',
        'code' => 'MATH',
        'departmentID' => '0002',
        'courseIDs' => ['00000172', '00000206'],
    ],
    'csec-office-administration' => [
        'category' => 'CSEC Office Administration',
        'code' => 'OA',
        'departmentID' => '0001',
        'courseIDs' => ['00000174', '00000208'],
    ],
    'csec-physics' => [
        'category' => 'CSEC Physics',
        'code' => 'PHY',
        'departmentID' => '0003',
        'courseIDs' => ['00000176', '00000210'],
    ],
    'csec-principles-of-accounts' => [
        'category' => 'CSEC Principles of Accounts',
        'code' => 'POA',
        'departmentID' => '0001',
        'courseIDs' => ['00000177', '00000211'],
    ],
    'csec-principles-of-business' => [
        'category' => 'CSEC Principles of Business',
        'code' => 'POB',
        'departmentID' => '0001',
        'courseIDs' => ['00000178', '00000212'],
    ],
    'csec-social-studies-july-2023' => [
        'category' => 'CSEC Social Studies',
        'code' => 'SS',
        'departmentID' => '0007',
        'courseIDs' => ['00000180', '00000214'],
    ],
];

$pdo = new PDO(
    sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4', $databaseServer, $databasePort, $databaseName),
    $databaseUsername,
    $databasePassword,
    [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]
);

function truncateText(string $text, int $maxLength): string
{
    $text = trim(preg_replace('/\s+/', ' ', $text) ?? $text);

    if (mb_strlen($text) <= $maxLength) {
        return $text;
    }

    $suffix = '...';
    $limit = $maxLength - mb_strlen($suffix);
    $truncated = mb_substr($text, 0, $limit);
    $lastSpace = mb_strrpos($truncated, ' ');

    if ($lastSpace !== false && $lastSpace > 0) {
        $truncated = mb_substr($truncated, 0, $lastSpace);
    }

    return rtrim($truncated) . $suffix;
}

function normalizeSpace(string $text): string
{
    return trim(preg_replace('/\s+/', ' ', $text) ?? $text);
}

function dbText(string $text): string
{
    $replacements = [
        '𝕎' => 'W',
        'ℕ' => 'N',
        'ℤ' => 'Z',
        'ℚ' => 'Q',
        'ℝ' => 'R',
        '𝜊' => 'o',
        '' => 'pi',
    ];
    $text = strtr($text, $replacements);

    return preg_replace('/[\x{10000}-\x{10FFFF}]/u', '', $text) ?? $text;
}

function loadJson(string $path): array
{
    $data = json_decode((string) file_get_contents($path), true);

    if (!is_array($data)) {
        throw new RuntimeException("Unable to parse JSON draft: {$path}");
    }

    return $data;
}

function getCourseNames(PDO $pdo, array $courseIDs): array
{
    if (empty($courseIDs)) {
        return [];
    }

    $placeholders = implode(',', array_fill(0, count($courseIDs), '?'));
    $statement = $pdo->prepare("SELECT gibbonCourseID, name FROM gibbonCourse WHERE gibbonCourseID IN ({$placeholders})");
    $statement->execute($courseIDs);

    $names = [];
    foreach ($statement->fetchAll() as $row) {
        $names[$row['gibbonCourseID']] = $row['name'];
    }

    return $names;
}

function findExistingUnit(PDO $pdo, string $courseID, string $seedKey, int $ordering): ?string
{
    $statement = $pdo->prepare(
        'SELECT gibbonUnitID FROM gibbonUnit
         WHERE gibbonCourseID = :gibbonCourseID
         AND ordering = :ordering
         AND tags LIKE :seedKey
         LIMIT 1'
    );
    $statement->execute([
        'gibbonCourseID' => $courseID,
        'ordering' => $ordering,
        'seedKey' => '%' . $seedKey . '%',
    ]);
    $id = $statement->fetchColumn();

    return $id === false ? null : (string) $id;
}

function findExistingOutcome(PDO $pdo, string $nameShort): ?string
{
    $statement = $pdo->prepare('SELECT gibbonOutcomeID FROM gibbonOutcome WHERE nameShort = :nameShort LIMIT 1');
    $statement->execute(['nameShort' => $nameShort]);
    $id = $statement->fetchColumn();

    return $id === false ? null : (string) $id;
}

function insertOutcome(PDO $pdo, array $data): string
{
    $sql = 'INSERT INTO gibbonOutcome SET scope=:scope, gibbonDepartmentID=:gibbonDepartmentID, name=:name, nameShort=:nameShort, active=:active, category=:category, description=:description, gibbonYearGroupIDList=:gibbonYearGroupIDList, gibbonPersonIDCreator=:gibbonPersonIDCreator';
    $statement = $pdo->prepare($sql);
    $statement->execute($data);

    return (string) $pdo->lastInsertId();
}

function insertUnit(PDO $pdo, array $data): string
{
    $sql = 'INSERT INTO gibbonUnit SET gibbonCourseID=:gibbonCourseID, name=:name, description=:description, tags=:tags, active=:active, map=:map, ordering=:ordering, license=:license, sharedPublic=:sharedPublic, attachment=:attachment, details=:details, gibbonPersonIDCreator=:gibbonPersonIDCreator, gibbonPersonIDLastEdit=:gibbonPersonIDLastEdit';
    $statement = $pdo->prepare($sql);
    $statement->execute($data);

    return (string) $pdo->lastInsertId();
}

function insertUnitBlock(PDO $pdo, array $data): string
{
    $sql = 'INSERT INTO gibbonUnitBlock SET gibbonUnitID=:gibbonUnitID, title=:title, type=:type, length=:length, contents=:contents, teachersNotes=:teachersNotes, sequenceNumber=:sequenceNumber';
    $statement = $pdo->prepare($sql);
    $statement->execute($data);

    return (string) $pdo->lastInsertId();
}

function insertUnitOutcome(PDO $pdo, array $data): string
{
    $sql = 'INSERT INTO gibbonUnitOutcome SET gibbonUnitID=:gibbonUnitID, gibbonOutcomeID=:gibbonOutcomeID, content=:content, sequenceNumber=:sequenceNumber';
    $statement = $pdo->prepare($sql);
    $statement->execute($data);

    return (string) $pdo->lastInsertId();
}

function buildDetails(array $draft, array $unit): string
{
    $lines = [
        'Generated from CSEC unit-plan draft.',
        'Source PDF: ' . ($draft['sourcePdf'] ?? ''),
    ];

    if (!empty($draft['warnings'])) {
        $lines[] = '';
        $lines[] = 'Document warnings:';
        foreach ($draft['warnings'] as $warning) {
            $lines[] = '- ' . $warning;
        }
    }

    if (!empty($unit['warnings'])) {
        $lines[] = '';
        $lines[] = 'Unit warnings:';
        foreach ($unit['warnings'] as $warning) {
            $lines[] = '- ' . $warning;
        }
    }

    if (!empty($unit['generalObjectives'])) {
        $lines[] = '';
        $lines[] = 'General Objectives:';
        foreach ($unit['generalObjectives'] as $index => $objective) {
            $lines[] = ($index + 1) . '. ' . $objective;
        }
    }

    return implode("\n", $lines);
}

function nextOutcomeCode(string $subjectCode, int $unitIndex, int $objectiveIndex): string
{
    return sprintf('%s-GO%02d-%02d', $subjectCode, $unitIndex, $objectiveIndex);
}

function normalizeDraftUnits(array $units): array
{
    $selectedByNumericSection = [];
    $normalized = [];

    foreach ($units as $index => $unit) {
        $title = normalizeSpace((string) ($unit['title'] ?? ''));
        if (preg_match('/^Section\s+(\d+)\b/i', $title, $matches)) {
            $selectedByNumericSection[$matches[1]] = $index;
        }
    }

    foreach ($units as $index => $unit) {
        $title = normalizeSpace((string) ($unit['title'] ?? ''));
        if (preg_match('/^Section\s+(\d+)\b/i', $title, $matches) && $selectedByNumericSection[$matches[1]] !== $index) {
            continue;
        }

        $normalized[] = $unit;
    }

    return $normalized;
}

$counts = [
    'subjects' => 0,
    'unitsInserted' => 0,
    'unitsSkipped' => 0,
    'blocksInserted' => 0,
    'outcomesInserted' => 0,
    'outcomesReused' => 0,
    'unitOutcomesInserted' => 0,
];

echo $commit ? "COMMIT MODE: database writes enabled.\n\n" : "DRY RUN: no database writes. Pass --commit to write.\n\n";

try {
    $pdo->beginTransaction();

    foreach ($subjectConfigs as $draftSlug => $config) {
        $path = $draftDir . '/' . $draftSlug . '.json';
        if (!is_file($path)) {
            throw new RuntimeException("Missing generated draft JSON: {$path}");
        }

        $draft = loadJson($path);
        $courseNames = getCourseNames($pdo, $config['courseIDs']);
        $counts['subjects']++;

        echo $config['category'] . "\n";
        echo '  Courses: ' . implode(', ', array_map(
            fn (string $id): string => $id . ' ' . ($courseNames[$id] ?? '[missing]'),
            $config['courseIDs']
        )) . "\n";
        $units = normalizeDraftUnits($draft['units'] ?? []);
        echo '  Draft units: ' . count($units) . "\n";

        foreach ($units as $unitIndex => $unit) {
            $unitNumber = $unitIndex + 1;
            $seedKey = 'CSEC-DRAFT-' . $config['code'] . '-U' . sprintf('%02d', $unitNumber);
            $unitTitle = normalizeSpace((string) ($unit['title'] ?? 'Unit ' . $unitNumber));
            $unitName = truncateText($unitTitle, 40);
            $description = $unitTitle . "\n\nSeed key: {$seedKey}";
            $details = buildDetails($draft, $unit);
            $tags = implode('; ', [$seedKey, $config['category'], 'CSEC Unit Plan Draft']);

            $outcomeIDs = [];
            foreach (($unit['generalObjectives'] ?? []) as $objectiveIndex => $generalObjective) {
                $nameShort = nextOutcomeCode($config['code'], $unitNumber, $objectiveIndex + 1);
                $existingOutcomeID = findExistingOutcome($pdo, $nameShort);

                if ($existingOutcomeID !== null) {
                    $outcomeIDs[] = [
                        'id' => $existingOutcomeID,
                        'content' => $generalObjective,
                    ];
                    $counts['outcomesReused']++;
                    continue;
                }

                if ($commit) {
                    $outcomeID = insertOutcome($pdo, [
                        'scope' => 'Learning Area',
                        'gibbonDepartmentID' => $config['departmentID'],
                        'name' => truncateText(dbText((string) $generalObjective), 100),
                        'nameShort' => $nameShort,
                        'active' => 'Y',
                        'category' => $config['category'],
                        'description' => dbText((string) $generalObjective),
                        'gibbonYearGroupIDList' => $yearGroupIDList,
                        'gibbonPersonIDCreator' => $creatorPersonID,
                    ]);
                    $outcomeIDs[] = [
                        'id' => $outcomeID,
                        'content' => $generalObjective,
                    ];
                }

                $counts['outcomesInserted']++;
            }

            foreach ($config['courseIDs'] as $courseID) {
                if (!isset($courseNames[$courseID])) {
                    throw new RuntimeException("Configured course ID {$courseID} was not found.");
                }

                $existingUnitID = findExistingUnit($pdo, $courseID, $seedKey, $unitNumber);
                if ($existingUnitID !== null) {
                    $counts['unitsSkipped']++;
                    echo "  - Skip existing {$courseNames[$courseID]} / {$unitTitle}\n";
                    continue;
                }

                if ($commit) {
                    $unitID = insertUnit($pdo, [
                        'gibbonCourseID' => $courseID,
                        'name' => dbText($unitName),
                        'description' => dbText($description),
                        'tags' => $tags,
                        'active' => 'Y',
                        'map' => 'Y',
                        'ordering' => $unitNumber,
                        'license' => '',
                        'sharedPublic' => 'N',
                        'attachment' => '',
                        'details' => dbText($details),
                        'gibbonPersonIDCreator' => $creatorPersonID,
                        'gibbonPersonIDLastEdit' => $creatorPersonID,
                    ]);
                } else {
                    $unitID = 'DRY-RUN-UNIT';
                }

                $counts['unitsInserted']++;

                foreach (($unit['specificObjectives'] ?? []) as $blockIndex => $objective) {
                    if ($commit) {
                        $blockTitle = trim((string) ($objective['sequence'] ?? '')) . ' ' . (string) ($objective['title'] ?? '');
                        insertUnitBlock($pdo, [
                            'gibbonUnitID' => $unitID,
                            'title' => truncateText(dbText($blockTitle), 100),
                            'type' => 'Learning',
                            'length' => '',
                            'contents' => dbText((string) ($objective['content'] ?: $objective['title'])),
                            'teachersNotes' => '',
                            'sequenceNumber' => (string) ($blockIndex + 1),
                        ]);
                    }
                    $counts['blocksInserted']++;
                }

                foreach ($outcomeIDs as $outcomeIndex => $outcome) {
                    if ($commit) {
                        insertUnitOutcome($pdo, [
                            'gibbonUnitID' => $unitID,
                            'gibbonOutcomeID' => $outcome['id'],
                            'content' => dbText((string) $outcome['content']),
                            'sequenceNumber' => (string) ($outcomeIndex + 1),
                        ]);
                    }
                    $counts['unitOutcomesInserted']++;
                }

                echo "  - Add {$courseNames[$courseID]} / {$unitTitle}\n";
            }
        }

        echo "\n";
    }

    if ($commit) {
        $pdo->commit();
    } else {
        $pdo->rollBack();
    }
} catch (Throwable $exception) {
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }

    fwrite(STDERR, "\nERROR: " . $exception->getMessage() . "\n");
    exit(1);
}

echo "Summary\n";
foreach ($counts as $key => $value) {
    echo "  {$key}: {$value}\n";
}

if (!$commit) {
    echo "\nNo database changes were made.\n";
}
